# SPDX-FileCopyrightText: 2015-2023 Alexey Rochev
#
# SPDX-License-Identifier: CC0-1.0

name: Build Tremotesf for Windows

on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: 'Choose toolchain'
        required: true
        default: 'windows-msvc-vcpkg'
        type: choice
        options:
          - windows-msvc-vcpkg
          - windows-msvc-clang-vcpkg

jobs:
  build-windows-msvc:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up MSVC environment
      uses: equeim/action-setup-msvc-environment@v1

    - name: Set VCPKG_ROOT environment variable
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> '${{ github.env }}'

    - name: Set up vcpkg
      uses: equeim/action-setup-vcpkg@v6
      with:
        run-install: true
        install-root: C:\vcpkg_installed
        triplet: x64-windows-static
        host-triplet: x64-windows-static
        overlay-triplets-path: ${{ github.workspace }}\src\libtremotesf\vcpkg-windows-overlay-triplets
        binary-cache-path: C:\vcpkg_binary_cache
        save-cache: ${{ github.event_name != 'pull_request' }}

    # We don't use matrix here because we want for vcpkg to install dependencies only once

    - name: Build Tremotesf
      id: build
      uses: equeim/action-cmake-build@v10
      with:
        cmake-arguments: --preset ${{ inputs.toolchain }} -D VCPKG_MANIFEST_INSTALL=OFF -D VCPKG_INSTALLED_DIR=C:\vcpkg_installed
        package: true

    # - name: Build Tremotesf with MSVC + Clang toolchain
    #   if: inputs.build-for-release == ''
    #   uses: equeim/action-cmake-build@v9
    #   with:
    #     cmake-arguments: --preset windows-msvc-clang-vcpkg -D VCPKG_MANIFEST_INSTALL=OFF -D VCPKG_INSTALLED_DIR=C:\vcpkg_installed
    #     output-directories-suffix: -clang

    - name: Archive packages
      # if: inputs.build-for-release == ''
      uses: actions/upload-artifact@v4
      with:
        name: windows-msvc-packages
        retention-days: ${{ github.event_name == 'push' && github.retention_days || 3 }}
        path: |
          ${{ steps.build.outputs.build-directory }}\windows-packaging\*Release.zip
